name: Checks

on:
  push:
    branches:
      - main

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Archive node_modules artifact
        uses: actions/upload-artifact@main
        with:
          name: node_modules
          path: node_modules

      - name: Run NPM check
        run: npm run check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@main
        with:
          name: node_modules
          path: node_modules

      - name: Run NPM build
        run: npm run build

      - name: Archive dist artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download dist artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE }}